package gxt.client.domain;

import java.math.BigDecimal;

import jpa.atm.AtPart;
import jpa.atm.ExtTermStat;
import jpa.atm.F250Town;

import com.google.web.bindery.requestfactory.shared.EntityProxy;
import com.google.web.bindery.requestfactory.shared.ProxyFor;

@ProxyFor(value = ExtTermStat.class, locator = gxt.server.domain.TermLoc.class)
public interface TermStPrx extends EntityProxy{
    public String getStatus();
    public long getId();
    public String getFinName();
    public String getAddr();
    public void setAddr(String addr);
    public String getDFr();
    public void setDFr(String dFr);
    public String getDFrAll();
    public void setDFrAll(String dFrAll);
    public String getDFrFr();
    public void setDFrFr(String dFrFr);
    public String getDFrTo();
    public void setDFrTo(String dFrTo);
    public String getDMo();
    public void setDMo(String dMo);
    public String getDMoAll();
    public void setDMoAll(String dMoAll);
    public String getDMoFr();
    public void setDMoFr(String dMoFr);
    public String getDMoTo();
    public void setDMoTo(String dMoTo);
    public String getDSa();
    public void setDSa(String dSa);
    public String getDSaAll();
    public void setDSaAll(String dSaAll);
    public String getDSaFr();
    public void setDSaFr(String dSaFr);
    public String getDSaTo();
    public void setDSaTo(String dSaTo);
    public String getDSu();
    public void setDSu(String dSu);
    public String getDSuAll();
    public void setDSuAll(String dSuAll);
    public String getDSuFr();
    public void setDSuFr(String dSuFr);
    public String getDSuTo();
    public void setDSuTo(String dSuTo);
    public String getDTh();
    public void setDTh(String dTh);
    public String getDThAll();
    public void setDThAll(String dThAll);
    public String getDThFr();
    public void setDThFr(String dThFr);
    public String getDThTo();
    public void setDThTo(String dThTo);
    public String getDTu();
    public void setDTu(String dTu);
    public String getDTuAll();
    public void setDTuAll(String dTuAll);
    public String getDTuFr();
    public void setDTuFr(String dTuFr);
    public String getDTuTo();
    public void setDTuTo(String dTuTo);
    public String getDWe();
    public void setDWe(String dWe);
    public String getDWeAll();
    public void setDWeAll(String dWeAll);
    public String getDWeFr();
    public void setDWeFr(String dWeFr);
    public String getDWeTo();
    public void setDWeTo(String dWeTo);
    public String getDol();
    public void setDol(String dol);
    public String getShi();
    public void setShi(String shi);
    public String getDop(); 
    public void setDop(String dop);
    public String getFin();
    public void setFin(String fin);
    public String getLocation();
    public void setLocation(String location);
    
    public String getpMoFr();
    public void setpMoFr(String pMoFr);
    public String getpMoTo();
    public void setpMoTo(String pMoTo);
    public String getpTuFr();
    public void setpTuFr(String pTuFr);
    public String getpTuTo();
    public void setpTuTo(String pTuTo);
    public String getpWeFr();
    public void setpWeFr(String pWeFr);
    public String getpWeTo();
    public void setpWeTo(String pWeTo);
    public String getpThFr();
    public void setpThFr(String pThFr);
    public String getpThTo();
    public void setpThTo(String pThTo);
    public String getpFrFr();
    public void setpFrFr(String pFrFr);
    public String getpFrTo();
    public void setpFrTo(String pFrTo);
    public String getpSaFr();
    public void setpSaFr(String pSaFr);
    public String getpSaTo();
    public void setpSaTo(String pSaTo);
    public String getpSuFr();
    public void setpSuFr(String pSuFr);
    public String getpSuTo();
    public void setpSuTo(String pSuTo);
    
    public F250TownPrx getF250Town();
    public BigDecimal getOId();
//    public String getPart();
    public PartPrx getAtPart();
    public void setAtPart(PartPrx atPart);
//    public String getPartName();

    public String getIsActive();
    public void setIsActive(String isActive);
    public void setIsForall(String isForall);
    public String getIsForall();
    public void setDaysNotrans(String daysNotrans);
    public String getDaysNotrans();
    
    public String getTerm();
    public OkatoPrx getAtOkato();
    public void setAtOkato(OkatoPrx atOkato);
    public String getTownString();
//    public int getCount();
    Integer getVersion();
}
